# Site settings
name: 一个简单的博客
email: 971866257@qq.com
author: Seashell113
github: https://github.com/Seashell113
baseurl: "/"
description: Do more , and speak less.
meta_description: 
motto: write to remmber.
banner: first step

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Seashell113

# Build settings
markdown: kramdown

baidu_analysis: 962ea55e8c9d4229106ac41e96c7f64c

